# Goal - To run End to End DevSecOps CI Pipeline

name: DevSecOps
on: [workflow_dispatch]

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml
    
    dependency-checks:
        uses: ./.github/workflows/secret-scanning.yml


    sonar_scan:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    code-tests:
        uses: ./.github/workflows/code-tests.yml

    docker-checks:
        uses: ./.github/workflows/docker-scans.yml
        secrets: inherit

    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-quality,code-tests,docker-checks,dependency-checks,secret-scanning,sonar_scan]
    
    deploy:
        uses: ./.github/workflows/deploy.yml
        needs: [docker-push]